# wasmer.toml
# Konfigurasi ini memberitahu Wasmer cara menjalankan aplikasi PHP Anda.
[package]
name = "id-card-generator"
version = "1.0.0"
description = "PHP Student ID Card Generator for Wasmer"

[[module]]
name = "app"
source = "wasmer/php@8.2.13" # Menggunakan paket PHP resmi dari Wasmer
abi = "wasi"

[command]
name = "generate"
module = "app"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
# Menjalankan server pengembangan PHP built-in pada port 80
# dan menggunakan direktori /app sebagai root dokumen.
main-args = [
    "-S",
    "0.0.0.0:80",
    "-t",
    "/app",
]

[fs]
# Memetakan direktori proyek Anda saat ini ('.') ke direktori /app
# di dalam wadah Wasmer.
"/app" = "."
